# Site settings
title: Akash Gutha
subtitle: Engineering Blog
email: akash.gutha@outlook.com
description: "Electronics - Code - OpenSource"
baseurl: ""
url: "https://akashgutha.github.io"
twitter_username: AkashGutha
github_username:  AkashGutha

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
plugins: ["jekyll-paginate"]

analytics :
  provider : google
  google:
    tracking_id : ''
  getclicky :
    site_id

plugins:
  - jemoji